### ISSUE TITLE
Display the numbers on the icon badges

### ISSUE THREAD

**Issue by DiegoRosales** [BigTechTalk/vscode-developers-dark-theme#1]
Overall I really like this theme. It is colorful and high contrast without being distracting. The only thing I would really like to have is the option to see the numbers on the side icon badges

![image](https://user-images.githubusercontent.com/6503118/132219480-cd6b9a3b-0501-4986-927f-5e0a5e930a12.png) ![image](https://user-images.githubusercontent.com/6503118/132219556-60364d8d-0929-414d-9705-b1d4da726353.png)

Additionally, for those icons, I don't mind the red color, but sometimes it's hard to see when you have glare in the monitor. Would it be possible to have an alternate version with a lighter color?

**Comment by BigTechTalk** [comment]
Issue fixed as recommended.

![image](https://user-images.githubusercontent.com/87256860/132358238-83a38a1f-8c3b-43a3-90c4-272067670510.png)

**Comment by DiegoRosales** [comment]
Awesome! Can't wait to try it :D

Thanks!

**Comment by DiegoRosales** [comment]
Fantastic! Thanks!!
![image](https://user-images.githubusercontent.com/6503118/132359787-85f77ff3-0a2b-4d13-80d2-4561e037f97f.png)
