### ISSUE TITLE
Increase the contrast of black text on blue background

### ISSUE THREAD

**Issue by DiegoRosales** [BigTechTalk/vscode-developers-dark-theme#2]
I've been using this theme for a while and I noticed that the black text on blue background is a little hard to read, especially since it's surrounded by black.
![image](https://user-images.githubusercontent.com/6503118/134297477-c0d175d7-a862-4a7f-9fe6-9cde6ae3210a.png)
![image](https://user-images.githubusercontent.com/6503118/134297515-5da3773b-d88f-4946-8777-1ff017400235.png)

Would it be possible to make the text a light color?

**Comment by BigTechTalk** [comment]
![image](https://user-images.githubusercontent.com/87256860/137669241-1cce8b31-bd4c-47b6-8482-5cd6092a615a.png)
Changes done. Have a look to it.

**Comment by BigTechTalk** [comment]
Closing issue as it is resolved.
